jobs/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('jobs_search.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

jobs_search/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'jobs_search'


urlpatterns = [

    #/
    url(r'^$', views.AnnoncesListView.as_view(), name='index'),

    #/annonce pk/
    url(r'^(?P<pk>[0-9]+)/$', views.AnnonceDetailView.as_view(), name='detail'),

    #/add/
    url(r'^add',views.CreateAnnonce.as_view(), name='create'),

    # /register/
    url(r'^register', views.UserFormView.as_view(), name='register'),

    # /login/
    url(r'^login', views.UserLoginFormView.as_view(), name='login'),

    # /logout/
    url(r'^logout', views.user_logout, name='logout'),

    # /list_annonces/
    url(r'^list_annonces', views.user_annonces_list, name='list_annonces'),

    # #/search_results/
    url(r'^search_results', views.search, name='search'),

]

jobs_search/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User


class Annonce(models.Model):

    domaines_list = (('technology', 'technology'), ('mechanics', 'mechanics'), ('commerce', 'commerce')
        , ('training and education', 'training and education'), ('services', 'services'), ('tourism', 'tourism'))



    region_list = (('sfax', 'sfax'), ('monastir', 'monastir'), ('gafsa', 'gafsa'), ('tunis', 'tunis')
        , ('sousse', 'sousse'), ('gabes', 'gabes'), ('mahdia', 'mahdia'), ('beja', 'beja')
        , ('tataouine', 'tataouine'),)

    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    domaine = models.CharField(max_length=100, choices = domaines_list, default=1)
    region = models.CharField(max_length=100, choices = region_list, default=1)
    description = models.TextField(max_length=1500)
    image = models.FileField()
    date = models.DateField(auto_now=True)
    phone = models.PositiveIntegerField()


    def get_absolute_url(self):
        return reverse('jobs_search:index')


    def __str__(self):
        return self.title

jobs_search/forms.py
from django.contrib.auth.models import User
from django import forms


class UserForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']


class UserLoginForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password']

jobs_search/views.py
from django.views import generic
from django.views.generic.edit import CreateView
from .models import Annonce
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.views.generic import View
from .forms import UserForm, UserLoginForm
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render


class AnnoncesListView(generic.ListView):

    template_name = "jobs_search/index.html"
    context_object_name = "all_annonces"
    paginate_by = 6

    def get_queryset(self):
        return Annonce.objects.order_by('-date')


class AnnonceDetailView (generic.DetailView):

    model = Annonce
    context_object_name = 'annonce'
    template_name = 'jobs_search/detail.html'


# @method_decorator(login_required, name='dispatch')
class CreateAnnonce(CreateView):

    template_name = "jobs_search/annonce_form.html"
    model = Annonce
    fields = ['title', 'domaine', 'region', 'description', 'image', 'phone']

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(CreateAnnonce, self).form_valid(form)

    # @method_decorator(login_required)
    # def dispatch(self, *args, **kwargs):
    #     return super(CreateAnnonce, self).dispatch(*args, **kwargs)


class UserFormView(View):

    # user registration view

    form_class = UserForm
    template_name = 'jobs_search/register.html'

    def get(self, request):

        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):

        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.username = username
            user.save()

            # return user object if credentials are correct

            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('jobs_search:index')

        return render(request, self.template_name, {'form': form})


class UserLoginFormView(View):

    # user login view

    form_class = UserLoginForm
    template_name = 'jobs_search/login.html'

    def get(self, request):

        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):

        form = self.form_class(request.POST)
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)

        if user is not None:

            login(request, user)
            return redirect('jobs_search:index')

        else:

            return render(request, self.template_name, {'form': form})


def user_logout(request):

    logout(request)
    return redirect('jobs_search:index')


def user_annonces_list(request):

    user = request.user
    list_annonces = user.annonce_set.all()
    context = {
        'list_annonces': list_annonces
    }
    return render(request, 'jobs_search/annonces_list.html', context)


def search(request):

    region = request.POST.get('region')
    domaine = request.POST.get('domaine')

    # annonces_region = Annonce.objects.filter(region__contains=region)
    # annonces_domaine = Annonce.objects.filter(domaine__contains=domaine)
    # annonces = annonces_region | annonces_domaine

    annonces = Annonce.objects.filter(region=region, domaine=domaine)

    return render(request, 'jobs_search/search_results.html', {'annonces': annonces})

jobs_search/templates/jobs_search/annonce_form.html
{% extends 'jobs_search/base.html'%}
{% block body%}
    <h1 style="text-align: center;">Add New Offer</h1>
    <br>
    <div  class="ui raised very padded text container segment">
        <form action="" method="post" enctype="multipart/form-data" class="ui form">
            {% csrf_token%}
            {% include 'jobs_search/form-template.html'%}
            <br>
            <br>
            <button class="positive ui big button" type="submit" style="margin-left: 40%">ADD</button>
            
        </form>
        {% endblock%}
    </div>

jobs_search/templates/jobs_search/annonces_list.html
{% extends 'jobs_search/base.html'%}
{%block body%}
<br>
{%if list_annonces%}
<h3 style="text-align: center;">My offers</h3>
{%for annonce in list_annonces%}
<br>

<div class="ui container">

    <div class="ui segment">
        <div class="ui items">
          <div class="item">
            <div class="image">
              <img src="{{annonce.image.url}}">
            </div>
            <div class="content">
              <a class="header" style='color:#21BA45' href="{% url 'jobs_search:detail' annonce.id%}">{{annonce.title}}</a>
              <br>
              <h5>{{annonce.owner}}</h5>
              <div class="extra">
                {{annonce.date}}
              </div>
              <div class="extra">
                {{annonce.region}}
              </div>
            </div>
          </div>

        </div>
    </div>
</div>
{%endfor%}
{%else%}
<h3 style="text-align: center;">you don't have any offers</h3>
{%endif%}
{%endblock%}

jobs_search/templates/jobs_search/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title></title>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        {%load staticfiles%}
        <link rel="stylesheet" href="{% static 'jobs_search/Semantic-UI-CSS-master/semantic.min.css'%}">
        <link rel="stylesheet" href="{% static 'jobs_search/Semantic-UI-CSS-master/semantic.css'%}">
        <script type="text/javascript" src="{% static 'jobs_search/Semantic-UI-CSS-master/semantic.js'%}"></script>
        <script type="text/javascript" src="{% static 'jobs_search/Semantic-UI-CSS-master/semantic.min.js'%}"></script>

   <!--      <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/semantic-ui/2.2.13/semantic.min.css"> -->
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.13/components/dropdown.js">
        </script>

        <script type="text/javascript">
        $('select.dropdown')
        .dropdown()
        ;
        </script>



    </head>
    <body>
        <div class="ui pointing large fixed menu">
          <a class="item" href="{% url 'jobs_search:index'%}" style='color:#21BA45'>
            <strong>JOBS</strong>
          </a>
          {% if request.user.is_authenticated%}
          <a class="item" href="{% url 'jobs_search:create'%}">
            Add New
          </a>
          {%endif%}
          {% if not request.user.is_authenticated%}
          <a class="item" href="{% url 'jobs_search:login'%}">
            Add New
          </a>
          {%endif%}
          <div class="right menu">

            {%if not request.user.is_authenticated%}
            <div class="item">
                <div class="ui buttons">
                    <a class="ui positive button" href="{%url 'jobs_search:login'%}">Sign in</a>
                    <div class="or"></div>
                    <a class="ui positive button" href="{%url 'jobs_search:register'%}">Sign up</a>
                </div>
            </div>
            {%endif%}

            {%if request.user.is_authenticated%}
                <div class="item">
                    <a style='color:black' href="{% url 'jobs_search:list_annonces'%}">
                    {{request.user.username.upper}}</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <a href="{%url 'jobs_search:logout'%}" style='color:black'><i class="sign out  big icon"></i></a>
                </div>
            {%endif%}



        </div>
        </div>
        <br><br><br>

    {%block body%}
    {%endblock%}

    </body>
</html>

jobs_search/templates/jobs_search/detail.html
{% extends 'jobs_search/base.html'%}
{%block body%}
<br>

<div class="ui container">

    <div class="ui segment">
        <div class="ui items">
          <div class="item">
            <div class="image">
              <img src="{{annonce.image.url}}">
            </div>
            <div class="content">
              <a class="header" style='color:#21BA45'>{{annonce.title}}</a>
              <br>
              <h5>{{annonce.owner}}</h5>
              <h5>{{annonce.domaine}}</h5>
              <div class="extra">
                <p>{{annonce.description}}</p>
              </div>
              <div class="extra">
                {{annonce.date}}
              </div>
              <div class="extra">
                {{annonce.region}}
              </div>
              <div class="extra">
                {{annonce.phone}}
              </div>
            </div>
          </div>

        </div>
    </div>
</div>
{%endblock%}

jobs_search/templates/jobs_search/form-template.html
<!-- <div class="ui grid" style="margin-left:30px; margin-right:30px"> -->
    {% for field in form%}



    <div class="field">
        <label>{{ field.label_tag}}</label>
        {{field}}
      </div>
      <br>





    <!-- <div class="three wide column"></div>
    
    <div class="three wide column">
        <label>
            <strong>{{ field.label_tag}}</strong>
        </label>
    </div>

    <div class="seven wide column">
        {{field}}
    </div>

    <div class="three wide column"></div> -->



    {% endfor%}
<!-- </div> -->

jobs_search/templates/jobs_search/index.html
{% extends 'jobs_search/base.html'%} {%block body%}

<div class="ui grid ">
    <div class="four wide column">
        <br>
        <div class="ui container">
            <div class="ui segment" style="position: fixed;width: 300px; margin-left: 10px;">
                <form action="{%url 'jobs_search:search'%}" method="POST" class="ui form">
                    {%csrf_token%}
                    <h3>region</h3>
                    <select name="region" class="ui fluid dropdown">
                         <option value="sfax">sfax</option>
                         <option value="monastir">monastir</option>
                         <option value="gafsa">gafsa</option>
                         <option value="tunis">tunis</option>
                         <option value="sousse">sousse</option>
                         <option value="gabes">gabes</option>
                         <option value="mahdia">mahdia</option>
                         <option value="beja">beja</option>
                         <option value="tataouine">tataouine</option>
                    </select>
                    <br>
                    <h3>domaine</h3>
                    <select name="domaine" class="ui dropdown" id="select">
                         <option value="technology">technology</option>
                         <option value="mechanics">mechanics</option>
                         <option value="commerce">commerce</option>
                         <option value="training and education">training and education</option>
                         <option value="services">services</option>
                         <option value="tourism">tourism</option>
                    </select>
                    <br><br>
                    <button class="positive ui compact labeled icon button" type="submit">
                <i class="search icon"></i>
                SEARCH
                </button>
                </form>
            </div>
        </div>
    </div>
    <div class="twelve wide column">
        {%for annonce in all_annonces%}
        <br>
        <div class="ui container">
            <div class="ui segment">
                <div class="ui items">
                    <div class="item">
                        <div class="image">
                            <img src="{{annonce.image.url}}">
                        </div>
                        <div class="content">
                            <a class="header" style='color:#21BA45' href="{% url 'jobs_search:detail' annonce.id%}">{{annonce.title}}</a>
                            <br>
                            <h5>{{annonce.owner}}</h5>
                            <div class="extra">
                                {{annonce.date}}
                            </div>
                            <div class="extra">
                                {{annonce.region}}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {%endfor%}
        <br> {% if is_paginated %}
        <div class="ui pagination menu">
            {% for i in paginator.page_range %} {% if page_obj.number == i %}
            <a class="active item"><span>{{ i }} </span></a> {% else %}
            <a href="?page={{ i }}" class="item">{{ i }}</a> {% endif %} {% endfor %}
        </div>
        {% endif %}
    </div>
</div>

{%endblock%}

jobs_search/templates/jobs_search/login.html
{% extends 'jobs_search/base.html'%}
{% block body%}
    <h1 style="text-align: center;">Sign In</h1>
    <br>
    <br>
    <div class="ui raised very padded text container segment">

        <form action="" method="post" enctype="multipart/form-data" class="ui form">
            {% csrf_token%}
            {% include 'jobs_search/form-template.html'%}
            <br>
            <br>
            <button type="submit" class="positive ui compact labeled icon big button" type="submit" style="margin-left: 40%"><i class="user icon"></i>Sign in</button>
        </form>
    </div>
{% endblock%}

jobs_search/templates/jobs_search/register.html
{% extends 'jobs_search/base.html'%}
{% block body%}
    <h1 style="text-align: center;">Sign Up</h1>
    <br>
    <br>
    <div class="ui raised very padded text container segment">
        <form action="" method="post" enctype="multipart/form-data" class="ui form">
            {% csrf_token%}
            {% include 'jobs_search/form-template.html'%}
            <br>
            <br>
            <button type="submit" class="positive ui compact labeled icon big button" type="submit" style="margin-left: 40%"><i class="add user icon"></i>Sign Up</button>
        </form>
    </div>
{% endblock%}

jobs_search/templates/jobs_search/search_results.html
{% extends 'jobs_search/base.html'%}
{%block body%}

<div class="ui grid ">
    <div class="four wide column">
        <br>
        <div class="ui container">
            <div class="ui segment" style="position: fixed;width: 300px; margin-left: 10px;" >

                <form action="{%url 'jobs_search:search'%}" method="POST" class="ui form">
                    {% csrf_token%}
                    <h3>region</h3>
                    <select name="region" class="ui fluid dropdown">
                         <option value="sfax">sfax</option>
                         <option value="monastir">monastir</option>
                         <option value="gafsa">gafsa</option>
                         <option value="tunis">tunis</option>
                         <option value="sousse">sousse</option>
                         <option value="gabes">gabes</option>
                         <option value="mahdia">mahdia</option>
                         <option value="beja">beja</option>
                         <option value="tataouine">tataouine</option>
                    </select>

                <br>

                    <h3>domaine</h3>
                    <select name="domaine" class="ui dropdown" id="select">
                         <option value="technology">technology</option>
                         <option value="mechanics">mechanics</option>
                         <option value="commerce">commerce</option>
                         <option value="training and education">training and education</option>
                         <option value="services">services</option>
                         <option value="tourism">tourism</option>

                    </select>

                <br><br>

                <button class="positive ui compact labeled icon button" type="submit">
                <i class="search icon"></i>
                SEARCH
                </button>
                </form>

            </div>

        </div>


    </div>
    {% if  annonces%}
    <div class="twelve wide column">
        {%for annonce in annonces%}
        <br>
        <div class="ui container">

            <div class="ui segment">
                <div class="ui items">
                  <div class="item">
                    <div class="image">
                      <img src="{{annonce.image.url}}">
                    </div>
                    <div class="content">
                      <a class="header" style='color:#21BA45' href="{% url 'jobs_search:detail' annonce.id%}">{{annonce.title}}</a>
                      <br>
                      <h5>{{annonce.owner}}</h5>
                      <div class="extra">
                        {{annonce.date}}
                      </div>
                      <div class="extra">
                        {{annonce.region}}
                      </div>
                    </div>
                  </div>

                </div>
            </div>
        </div>
        {%endfor%}
        {%else%}
    <div class="twelve wide column"> <br><br><br><strong style=" margin-left: 40% ;font-size:50px;">
    no results
  </strong></div>
    </div>    
    {%endif%}










</div>





{%endblock%}